### ISSUE TITLE
Upgrading to new version (`0.37.1`) gives assembly script errors

### ISSUE THREAD

**Issue by dmelotik** [graphprotocol/graph-tooling#1022]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

Using the latest `graph-cli` version we get non-descript assemblyscript errors when we have a pattern of comparing `BigInt`s that could be negative, but are not checked. Yes, this is a developer error. But the output looks like the snippet below so it is difficult to track down.

```✖ Failed to compile subgraph: Failed to compile data source template: The AssemblyScript compiler crashed when compiling this file: 'src/mappings/QiStablecoin.ts'
Suggestion: try to comment the whole file and uncomment it little by little while re-running the graph-cli until you isolate the line where the problem happens.
Also, please contact us so we can make the CLI better by handling errors like this. You can reach out in any of these links:
- Discord channel: https://discord.gg/eM8CA6WA9r
- Github issues: https://github.com/graphprotocol/graph-cli/issues
Error: Failed to compile data source template: The AssemblyScript compiler crashed when compiling this file: 'src/mappings/QiStablecoin.ts'
```

### Reproduction

NA

### Steps to Reproduce the Bug or Issue

This [line](https://github.com/messari/subgraphs/blob/47d365cbe2019371a50525fe4938056b744596fb/subgraphs/rocket-pool/src/mappings/rocketRewardsPoolMapping.ts#L97) is the problem when you try to build using `graph-cli` version 0.37.1

### Expected behavior

I would expect to see a cleaner subgraph compile error: 

```
Compile subgraphERROR TS2322: Type '~lib/@graphprotocol/graph-ts/common/numbers/BigInt | null' is not assignable to type '~lib/@graphprotocol/graph-ts/common/numbers/BigInt'.

   if (token.lastPriceBlockNumber && token.lastPriceBlockNumber.equals(event.block.number)) {
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
 in src/entities/price.ts(20,37)
```

### Platform

- OS: macOS
- NodeJS: v16.17.0
- `@graphprotocol/*` version(s): 0.37.1

**Comment by dotansimha** [comment]
Hi @dmelotik , did you try latest release `@graphprotocol/graph-cli@0.37.6`? We pushed a few fixes there

**Comment by dmelotik** [comment]
@dotansimha We will try that on our subgraph that we are currently facing the issue

**Comment by dmelotik** [comment]
@dotansimha I updated another subgraph from version `0.32.0` to `0.37.7` and I had another assemblyscript error:

Old:
```typescript
  if (block.gasLimit && block.gasLimit > BIGINT_ZERO && block.gasUsed)
```

Fix:
```typescript
  if (block.gasLimit && block.gasLimit! > BIGINT_ZERO && block.gasUsed)
```

**Comment by dotansimha** [comment]
> @dotansimha I updated another subgraph from version `0.32.0` to `0.37.7` and I had another assemblyscript error:
> 
> Old:
> 
> ```ts
>   if (block.gasLimit && block.gasLimit > BIGINT_ZERO && block.gasUsed)
> ```
> 
> Fix `block.gasLimit!`
> 
> ```ts
>   if (block.gasLimit && block.gasLimit! > BIGINT_ZERO && block.gasUsed)
> ```

This seems like a different issue maybe? I guess the bump from 32 to 37 has some other changes? @evaporei what do you think?

**Comment by evaporei** [comment]
The `block.gasLimit!` one doesn't make much sense to me, if it's from our types in `graph-ts`, that hasn't changed in months: https://github.com/graphprotocol/graph-ts/blame/main/chain/ethereum.ts#L537.

And I think the `token.lastPriceBlockNumber` error is probably because of an AssemblyScript compiler fix, prior the language used to accept equality comparisons between the same type independent if the value is nullable or not, for example:

```typescript
let nonNullable: BigInt = /* ... */
let nullable: BigInt | null = /* ... */

// this was possible in older versions
nonNullable == nullable

// but now it's checked by the compiler, and the nullable value should
// unwrap the null
nonNullable! == nullable
```

**Comment by dmelotik** [comment]
@evaporei the `block.gasLimit` thing is from 6 or 7 months ago, that may be why.

My next question, should the new changes catch those assemblyscript errors wrap it into a nicer error message? Without knowing this, debugging is pretty opaque.

**Comment by saihaj** [comment]
I have added as action items we can address in future
- https://github.com/graphprotocol/graph-tooling/issues/1072
- https://github.com/graphprotocol/graph-tooling/issues/1073
